stages:
- pytest
- sast

pytest:
  stage: pytest
  image: python:3.10-bullseye
  script:
    - python -m pip install -r requirements.txt
    - python -m pytest --junitxml=pytest.xml
  artifacts:
      paths:
        - pytest.xml
      reports:
        junit: pytest.xml

sast:
  stage: sast
include:
- template: Security/SAST.gitlab-ci.yml
